### ISSUE TITLE
Add ExpenseTrackerApp

### ISSUE THREAD

**Issue by CrypticRevenger** [sadanandpai/frontend-mini-challenges#212]
Creating a simple Expense Tracker using JavaScript. we can further use the design and functionality to match your specific requirements. 

![Screenshot (471)](https://github.com/sadanandpai/frontend-mini-challenges/assets/128175097/15a4aaa7-1eed-43f4-a8b5-2a45015bf685)

@sadanandpai Please assign me, I want to work on it.

**Comment by arpansaha13** [comment]
Expense tracker is already added

In vanilla JS
https://sadanandpai.github.io/frontend-mini-challenges/native/machine-coding/finance-tracker/

In React
https://sadanandpai.github.io/frontend-mini-challenges/react/dist/#/expense-tracker

Instead of creating a new challenge for this, you may add more features or fix bugs in the already implemented challenges above
